// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using competitions.Infrastructure.Services;

#nullable disable

namespace competitions.Migrations
{
    [DbContext(typeof(DatabaseService))]
    [Migration("20260325175728_AddTournamentStagesAndMaxParticipants")]
    partial class AddTournamentStagesAndMaxParticipants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("competitions.Infrastructure.Entities.CompetitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("BestOf")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("MapPool")
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.DivisionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("BestOf")
                        .HasColumnType("integer");

                    b.Property<string>("CompetitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxTeamsPerGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.DivisionGroupEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DivisionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("DivisionGroups");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.DivisionGroupStandingsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Standings");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.DivisionGroupStandingsEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("StandingsEntities");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.DivisionGroupTeamEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("DivisionGroupTeams");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.LeagueConfigEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompetitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRegistrationOpen")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LeaguePeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeaguePeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Legs")
                        .HasColumnType("integer");

                    b.Property<string>("OrganiserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganiserSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RealmSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegistrationPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RegistrationPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("LeagueConfigs");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.LeagueEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganiserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganiserSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RealmSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LeagueEntity");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.LeagueTeamEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeagueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("LeagueTeams");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.MatchEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AwayTeamId")
                        .HasColumnType("text");

                    b.Property<string>("CompetitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HomeTeamId")
                        .HasColumnType("text");

                    b.Property<string>("LoserTeamId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Round")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreAway")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreHome")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WinnerTeamId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.RosterEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeagueTeamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LeagueTeamId1")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeagueTeamId1");

                    b.ToTable("Rosters");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.RosterPlayerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RosterId")
                        .HasColumnType("integer");

                    b.Property<long>("RosterId1")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RosterId1");

                    b.ToTable("RosterPlayerEntity");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.TournamentConfigEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("BracketReset")
                        .HasColumnType("boolean");

                    b.Property<string>("CompetitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<string>("OrganiserId")
                        .HasColumnType("text");

                    b.Property<string>("RealmId")
                        .HasColumnType("text");

                    b.Property<int>("SeedingType")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("TournamentConfigs");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.TournamentStageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Advancing")
                        .HasColumnType("integer");

                    b.Property<string>("CompetitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<string>("FormatConfigJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("TournamentStages");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.DivisionEntity", b =>
                {
                    b.HasOne("competitions.Infrastructure.Entities.CompetitionEntity", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.DivisionGroupEntity", b =>
                {
                    b.HasOne("competitions.Infrastructure.Entities.DivisionEntity", "Division")
                        .WithMany("Groups")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.DivisionGroupTeamEntity", b =>
                {
                    b.HasOne("competitions.Infrastructure.Entities.DivisionGroupEntity", "Group")
                        .WithMany("Teams")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.LeagueConfigEntity", b =>
                {
                    b.HasOne("competitions.Infrastructure.Entities.CompetitionEntity", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.LeagueTeamEntity", b =>
                {
                    b.HasOne("competitions.Infrastructure.Entities.LeagueEntity", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.MatchEntity", b =>
                {
                    b.HasOne("competitions.Infrastructure.Entities.CompetitionEntity", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.RosterEntity", b =>
                {
                    b.HasOne("competitions.Infrastructure.Entities.LeagueTeamEntity", "LeagueTeam")
                        .WithMany()
                        .HasForeignKey("LeagueTeamId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueTeam");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.RosterPlayerEntity", b =>
                {
                    b.HasOne("competitions.Infrastructure.Entities.RosterEntity", "Roster")
                        .WithMany("Players")
                        .HasForeignKey("RosterId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.TournamentConfigEntity", b =>
                {
                    b.HasOne("competitions.Infrastructure.Entities.CompetitionEntity", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.TournamentStageEntity", b =>
                {
                    b.HasOne("competitions.Infrastructure.Entities.CompetitionEntity", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.DivisionEntity", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.DivisionGroupEntity", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.LeagueEntity", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("competitions.Infrastructure.Entities.RosterEntity", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
